name: build-release-image

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Maven cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Get Driver Version
        run: export VERSION=$(./scripts/get_version.sh)
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build image
        run: docker build --target stg_export --output target .
      - uses: actions/upload-artifact@v3
        with:
          name: ocient.metabase-driver.jar-{{VERSION}}
          path: ./target/ocient.metabase-driver.jar